### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by ThuriyaThwin** [emkor/n-queen-problem#1]
I have cloned your project in pycharm and run with python intrepreter 3.7.
These are errors while running startup.py
![untitled](https://user-images.githubusercontent.com/16722405/52400055-6fed9380-2aec-11e9-9cdd-cb9ab40cdfad.png)
"C:\Program Files (x86)\Python\python.exe" C:/Users/Administrator/PycharmProjects/n-queen-problem/startup.py
Traceback (most recent call last):
File "C:/Users/Administrator/PycharmProjects/n-queen-problem/startup.py", line 14, in 
params=[BOARD_SIZE, CONSTRAINTS, get_all_positions])
File "C:\Users\Administrator\PycharmProjects\n-queen-problem\utils.py", line 75, in run_multiple_times
board, stats = function(*params)
File "C:\Users\Administrator\PycharmProjects\n-queen-problem\csp.py", line 46, in csp
log("Initializing with {} as new value generator".format(new_value_selector_function.func_name))
AttributeError: 'function' object has no attribute 'func_name'

Process finished with exit code 1

**Comment by ThuriyaThwin** [comment]
"C:\Program Files (x86)\Python\python.exe" C:/Users/Administrator/PycharmProjects/n-queen-problem/startup.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/n-queen-problem/startup.py", line 14, in <module>
    params=[BOARD_SIZE, CONSTRAINTS, get_all_positions])
  File "C:\Users\Administrator\PycharmProjects\n-queen-problem\utils.py", line 75, in run_multiple_times
    board, stats = function(*params)
  File "C:\Users\Administrator\PycharmProjects\n-queen-problem\csp.py", line 46, in csp
    log("Initializing with {} as new value generator".format(new_value_selector_function.func_name))
AttributeError: 'function' object has no attribute 'func_name'

Process finished with exit code 1

**Comment by emkor** [comment]
@ThuriyaThwin yup, you're right; the project was written for Python 2, info on it is in the project tags. I have no plans for porting it to Python 3, but feel free to fork it :)
